server:
  port: 9418

spring:
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
